#version: '3.8'
#
#services:
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - my-network
#
#  nodejs-app:
#    build: .
#    ports:
#      - "3000:3000"
#    depends_on:
#      - redis
#    networks:
#      - my-network
#
#networks:
#  my-network:
#    driver: bridge


version: '3.8'

services:
  redis-stack:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight GUI
    networks:
      - my-network

  nodejs-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis-stack
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
